name: Generate Snake Animation

on:
  schedule:
    - cron: "0 23 * * 0"  # Sun 23:00 UTC = Mon 4 AM PKT, weekly
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Generate Snake Game with Light and Dark Themes
      - name: Generate Snake Game (Light and Dark Themes)
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.svg?palette=github
            dist/github-contribution-grid-snake-ocean.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Step 3: List Generated Files
      - name: List Generated Files
        run: ls -R dist

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
